# Generated by Django 4.1 on 2022-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
